server.port=8080
spring.application.name=pliki-api

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

logging.level.com.event.plikiapi=INFO
